name: release
on:
  release:
    types: [ 'created' ]

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    env:
      TARGET_FILE: aria-vscode-${{ github.event.release.tag_name }}
    steps:
      - uses: actions/setup-node@v1
        with:
          node-version: '14'
      - uses: actions/checkout@v2
      - run: mkdir -p dist
      - run: npm ci
      - run: npm run package
      - run: zip -r ${{ env.TARGET_FILE }}.zip dist
      - uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ${{ env.TARGET_FILE }}.zip
          asset_name: ${{ env.TARGET_FILE }}.zip
          asset_content_type: application/zip
      - uses: sarisia/actions-status-discord@v1
        if: always()
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK }}
          status: ${{ job.status }}
          title: "${{ env.TARGET_FILE }} released!"
